import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "../components/header/header";
import ThemeProvider from '@/context/themeProvider'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      <body>
        <ThemeProvider>
        {children}
        </ThemeProvider>
        </body>
        
    </html>
  );
}
